name: Annotation

on: push

jobs:
    log:
        runs-on: ubuntu-latest
        steps:
            - run: echo "::echo::This is an error"
            - run: echo "::warning::This is a warinig"
            - run: echo "::notice::This is a notice"
            